apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-app 
  name: node-app
spec:
  type: NodePort
  selector:
    app: node-app-1
  ports:
    - protocol: TCP
      port: 31007
      targetPort: 3000

